security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: '%bcrypt_cost%'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~
            provider: user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: homepage
                always_use_default_target_path: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: ROLE_USER }
