version: '3.3'

services:
    web:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./:/code
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        build: ./docker/php/.
        volumes:
            - ./:/code
            - ./docker/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./.data/db:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
