version: '3.3'

services:
    web:
        build: ./docker/nginx/.
        ports:
            - 8000:80
        volumes:
            - ./:/code

    php:
        build: ./docker/php/.
        volumes:
            - ./:/code
            - ./docker/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

    db:
        image: postgres:10.3
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./.data/db:/var/lib/postgresql/data
        ports:
            - 5432:5432
