version: '3.3'

services:
    web:
        build: ./docker/nginx/.
        ports:
            - 8000:80
        volumes:
            - ./:/code

    php:
        build: ./docker/php/.
        volumes:
            - ./:/code
            - ./docker/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./.data/db:/var/lib/mysql
        ports:
          - 3306:3306
