version: '3'
services:
    web:
        build: nginx/.
        ports:
            - '8000:80'
        volumes:
            - ../.:/code
        networks:
            - code-network

    php:
        build: php/.
        volumes:
            - ../.:/code
            - ../log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
