parameters:
    locale: 'ru'
    bcrypt_cost: 13

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface:
        class: Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder
        arguments:
            - '%bcrypt_cost%'
